export const UNIDADES_SAT = [
  { value: 'ACT', label: 'ACT - Actividad' },
  { value: 'H87', label: 'H87 - Pieza' },
  { value: 'E48', label: 'E48 - Unidad de servicio' },
  { value: 'KGM', label: 'KGM - Kilogramo' },
  { value: 'LTR', label: 'LTR - Litro' },
  { value: 'XBX', label: 'XBX - Caja' },
  { value: 'XKI', label: 'XKI - Kit' },
  { value: 'XLT', label: 'XLT - Lote' },
  { value: 'DAY', label: 'DAY - Día' },
  { value: 'HUR', label: 'HUR - Hora' },
  { value: 'MON', label: 'MON - Mes' },
  { value: 'ANN', label: 'ANN - Año' },
  { value: 'MTR', label: 'MTR - Metro' },
  { value: 'MTK', label: 'MTK - Metro cuadrado' },
  { value: 'MTQ', label: 'MTQ - Metro cúbico' },
  { value: 'SET', label: 'SET - Conjunto' },
  { value: 'GRM', label: 'GRM - Gramo' },
  { value: 'TNE', label: 'TNE - Tonelada' },
];